### ISSUE TITLE
Let's talk design/UX

### ISSUE THREAD

**Issue by ayzaan** [bksim/wikisurf#9]
One example is: http://mapsaurus.com/viewer?start=com-facebook-katana

I like the way it redisplays when a node is clicked.

Also for reading articles, check out http://ptable.com/ - when you click on an element, the wiki article pops up with the printable version, so it's easy to read. I can probably extract the html from the printable version and paste it  directly onto our page (so we can add our own css styles, etc.) I can do that or get it from the mediawiki api, where I can get each section as html: http://en.wikipedia.org/w/api.php?action=mobileview&page=Computer&prop=text&sections=all

**Comment by ayzaan** [comment]
Looking at the d3js.org library it seems like its more customizable/powerful?

**Comment by bksim** [comment]
Nice. I'm not a huge fan of the printable version (which is what we're doing in the current build of 'master') because the links aren't colored correctly and it looks..bland. The html might be nicer.

We do have to figure out UX though, as currently in arbor clicking and dragging allows repositioning of nodes. Regardless of which graphing js library we choose, we should decide what clicks, mouseovers, etc. do.

Do we care about giving the user the ability to click and drag nodes? Otherwise, the graph will be static, and we can make mouseovers the 'scrollto' feature in the wiki text and clicks the 'change graph center' feature.

**Comment by ayzaan** [comment]
Yeah printable version is bland. Ill play around with different things to see what works best.

Yeah we might have to try several different things to see whats best in terms of usability (mouseover, clicking nodes, etc)

I can't see any good reason someone would want to drag nodes around. I think a static graph would be easier to use.

**Comment by bksim** [comment]
Okay, great. We just need to make sure the labels don't get on top of each other and we can't see (so we should use some kind of spring model for the labels). The reason I wanted to move nodes before was because the labels sometimes covered each other up.

If we fix that problem, then mouseover could be scroll and click could be reposition?

**Comment by ayzaan** [comment]
I set up the site on heroku.

Check out this example of embedded wiki content: http://wikisurf.herokuapp.com/wiki/Computer. This is extracted html from the mediawiki api. We could add our own styles to make it look exactly how we want.

Yeah for now I guess mouseover could be scroll, but I think the page should stay scrolled unless they mouse over another node. And yes, click could be repositioned.

**Comment by ayzaan** [comment]
Also, for the embedded wiki content, we could reposition sections/content easily as we please. For one thing, I think we should take out or reposition the toc.
